workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:  # تعريف المتغيرات مباشرة بدلاً من المجموعات
        FLUTTER_VERSION: "3.22.2"
        FIREBASE_API_KEY: $FIREBASE_API_KEY  # سيتم تعريفها في إعدادات Codemagic
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    scripts:
      - name: 🛠️ إعداد البيئة
        script: |
          flutter version $FLUTTER_VERSION
          flutter doctor -v
          npm install -g firebase-tools@latest --force

      - name: 🧹 تنظيف المشروع
        script: |
          flutter clean
          rm -rf android/app/src/main/java/io/flutter/plugins/
          rm -rf android/app/src/main/kotlin/io/flutter/

      - name: 🔄 تحديث التبعيات
        script: |
          flutter pub get
          cd android && ./gradlew clean

      - name: 🏗️ بناء APK
        script: |
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --split-debug-info=./debug_info \
            --verbose

          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "❌ فشل البناء - لم يتم إنشاء APK"
            ls -la build/app/outputs/
            exit 1
          fi

      - name: 📤 نشر على Firebase
        script: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/service-account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --service-account-json /tmp/service-account.json \
            --groups "testers" \
            --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - debug_info/**
    publishing:
      email:
        recipients:
          - "your.email@example.com"
        notify:
          success: true
          failure: true
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
