workflows:
  android-release:
    name: Android Release Workflow
    environment:
      vars:
        FLUTTER_VERSION: "3.32.4"
      flutter: $FLUTTER_VERSION
    scripts:
      - name: Clean Environment
        script: |
          echo "=== تنظيف البيئة ==="
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches

      - name: Fix Gradle Files
        script: |
          echo "=== إصلاح ملفات Gradle ==="
          cd android
          # تأكد من حذف ملف الإعدادات القديم إن وجد
          rm -f settings.gradle.kts
          # منح صلاحيات تنفيذ لـ gradlew
          chmod +x gradlew
          cd ..

      - name: Setup Flutter
        script: |
          echo "=== إعداد Flutter ==="
          flutter pub get

      - name: Build APK
        script: |
          echo "=== بناء APK ==="
          flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
