workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      groups:
        - firebase_credentials
      vars:
        FLUTTER_VERSION: "3.19.5"
    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: 🛠️ إعداد البيئة
        script: |
          flutter version $FLUTTER_VERSION
          flutter doctor -v
          
          # حل مشكلة Firebase CLI
          sudo rm -f /usr/local/bin/firebase
          npm install -g firebase-tools@latest --force

      - name: 🏗️ بناء APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --split-debug-info=./debug_info
          
          # التحقق من وجود الملف
          APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          if [ ! -f "$APK_PATH" ]; then
            echo "❌ Error: APK file not found!"
            ls -la build/app/outputs/flutter-apk/
            exit 1
          fi

      - name: 📤 نشر على Firebase
        script: |
          # استخدام Service Account كبديل آمن
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --service-account-json "$FIREBASE_SERVICE_ACCOUNT_JSON" \
            --groups "testers" \
            --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - debug_info/**
    publishing:
      email:
        recipients:
          - "your-email@example.com"
        notify:
          success: true
          failure: true
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
