workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      groups:
        - firebase  # اسم المجموعة التي أنشأتها
      vars:
        FLUTTER_VERSION: "3.22.2"
        GRADLE_VERSION: "8.1.0"
        KOTLIN_VERSION: "1.9.22"
    
    scripts:
      - name: ⬇️ تثبيت Flutter
        script: |
          export FLUTTER_HOME="$HOME/programs/flutter"
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION $FLUTTER_HOME
          export PATH="$FLUTTER_HOME/bin:$PATH"
          flutter doctor -v

      - name: 🔧 إعداد Firebase
        script: |
          echo $FIREBASE_SERVICE_ACCOUNT_JSON > /tmp/firebase_account.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/firebase_account.json"
          firebase login:ci --token $FIREBASE_TOKEN

      - name: 🏗️ بناء APK
        script: |
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID

      - name: 🚀 النشر على Firebase App Distribution
        script: |
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --token $FIREBASE_TOKEN
    
    artifacts:
      - build/app/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - your.email@example.com
