workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:
        FLUTTER_VERSION: "3.22.2"  # استخدام أحدث إصدار مستقر
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    scripts:
      - name: 🧹 تنظيف شامل
        script: |
          flutter clean
          rm -rf android/
          rm -rf ios/
          rm -rf .flutter-plugins
          rm -rf .flutter-plugins-dependencies

      - name: 🛠️ إعداد البيئة من الصفر
        script: |
          flutter version $FLUTTER_VERSION
          flutter doctor -v
          
          # إعادة إنشاء المشروع بالكامل
          flutter create --platforms android --org com.yourcompany .
          
          flutter pub get
          npm install -g firebase-tools@latest --force

      - name: 🔄 تحديث التبعيات
        script: |
          flutter pub upgrade --major-versions
          cd android && ./gradlew clean

      - name: 🏗️ بناء APK نهائي
        script: |
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --verbose
          
          if [ ! -f "build/app/outputs/flutter-apk/app-release.apk" ]; then
            echo "❌ فشل البناء - لم يتم إنشاء APK"
            echo "🔍 محتويات مجلد البناء:"
            ls -la build/app/outputs/ || true
            exit 1
          else
            echo "✔ تم البناء بنجاح!"
            du -h build/app/outputs/flutter-apk/app-release.apk
          fi

      - name: 📤 نشر على Firebase
        script: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/service-account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --service-account-json /tmp/service-account.json \
            --groups "testers" \
            --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - "gogom8870@gmail.com"
        notify:
          success: true
          failure: true
