workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:
        FLUTTER_VERSION: "3.22.2"
        GRADLE_VERSION: "8.1.0"
        KOTLIN_VERSION: "1.9.22"
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    
    scripts:
      - name: ⬇️ تثبيت Flutter
        script: |
          export FLUTTER_HOME="$HOME/programs/flutter"
          rm -rf $FLUTTER_HOME
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION $FLUTTER_HOME
          export PATH="$FLUTTER_HOME/bin:$PATH"
          flutter channel stable
          flutter doctor -v

      - name: 🛠️ إنشاء هيكل Android
        script: |
          # إنشاء هيكل Android إذا لم يكن موجوداً
          if [ ! -d "android" ]; then
            echo "Creating Android project structure..."
            flutter create --platforms android .
          fi
          
          # إنشاء ملفات Gradle الأساسية إذا لم تكن موجودة
          if [ ! -f "android/gradle/wrapper/gradle-wrapper.properties" ]; then
            echo "Generating Gradle wrapper files..."
            cd android
            gradle wrapper --gradle-version $GRADLE_VERSION --distribution-type bin
            cd ..
          fi
          
          # تحديث إصدار Gradle
          echo "Updating Gradle to version $GRADLE_VERSION..."
          sed -i '' "s/gradle-.*.zip/gradle-$GRADLE_VERSION-bin.zip/g" android/gradle/wrapper/gradle-wrapper.properties
          
          # إنشاء/تحديث local.properties
          echo "Generating local.properties..."
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          
          # منح صلاحيات التنفيذ لملفات Gradle
          chmod +x android/gradlew

      - name: 🔄 تحديث التبعيات
        script: |
          flutter pub get
          cd android && ./gradlew clean && cd ..

      - name: 🏗️ بناء APK
        script: |
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --verbose

      - name: 🚀 النشر على Firebase
        script: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase_account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --service-account-json /tmp/firebase_account.json
    
    artifacts:
      - build/app/outputs/**/*.apk
      - android/gradle/wrapper/gradle-wrapper.properties
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
        - $FLUTTER_HOME/.pub-cache
