workflows:
  android-release:
    name: Android Release Workflow
    environment:
      groups:
        - firebase
      vars:
        FLUTTER_VERSION: "3.32.4"
        GRADLE_VERSION: "7.5"
        KOTLIN_VERSION: "1.7.20"
      flutter: $FLUTTER_VERSION
    scripts:
      # ========== مرحلة الإعداد ==========
      - name: Set Up Environment
        script: |
          echo "=== تنظيف البيئة ==="
          flutter channel stable
          flutter upgrade --force
          flutter clean
          
          echo "=== تنظيف Gradle ==="
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches
          ./gradlew --stop
          
          echo "=== إصلاح الأذونات ==="
          find android -type f -name "*.gradle" -exec chmod 644 {} \;
          chmod +x ./gradlew

      # ========== تثبيت التبعيات ==========
      - name: Install Dependencies
        script: |
          echo "=== تثبيت التبعيات ==="
          flutter pub get
          
          cd android
          ./gradlew clean

      # ========== مرحلة البناء ==========
      - name: Build APK
        script: |
          echo "=== بناء APK ==="
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID

      # ========== النشر ==========
      - name: Publish to Firebase App Distribution
        script: |
          echo "=== النشر على Firebase ==="
          echo $FIREBASE_SERVICE_ACCOUNT_JSON > firebase_credentials.json
          flutter pub run flutterfire_cli distribute \
            --release=build/app/outputs/flutter-apk/app-release.apk \
            --credentials-file=firebase_credentials.json

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
