workflows:
  android-release:
    name: Android Release Workflow
    environment:
      vars:
        FLUTTER_VERSION: "3.32.4"
      flutter: $FLUTTER_VERSION
    scripts:
      - name: Clean Environment
        script: |
          echo "=== تنظيف البيئة ==="
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches

      - name: Verify Project Structure
        script: |
          echo "=== التحقق من هيكل المشروع ==="
          if [ ! -d "android/app" ]; then
            echo "خطأ: مجلد android/app غير موجود!"
            exit 1
          fi
          if [ ! -f "android/settings.gradle" ]; then
            echo "إنشاء ملف settings.gradle جديد"
            echo "include ':app'" > android/settings.gradle
          fi

      - name: Setup Flutter
        script: |
          echo "=== إعداد Flutter ==="
          flutter pub get

      - name: Build APK
        script: |
          echo "=== بناء APK ==="
          cd android
          chmod +x gradlew
          ./gradlew clean
          cd ..
          flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
