################################################################
# WiMax Security Tester - Flutter Production Build
# تم التهيئة ليعمل مع المتغيرات الفردية بدون مجموعات
################################################################

workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:  # استخدام متغيرات فردية مباشرة
        ENCODED_KEYSTORE: $ENCODED_KEYSTORE
        STORE_PWD: $STORE_PWD
        KEY_PWD: $KEY_PWD
        KEY_ALIAS: $KEY_ALIAS
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_TOKEN: $FIREBASE_TOKEN
    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      # ======================
      # 1. إعداد توقيع التطبيق
      # ======================
      - name: 🔐 إعداد Keystore
        script: |
          mkdir -p android/app/keystore
          echo $ENCODED_KEYSTORE | base64 --decode > android/app/keystore/release.jks
          chmod 600 android/app/keystore/release.jks
          echo "✔ تم تحضير ملف التوقيع بنجاح"

      # ======================
      # 2. بناء التطبيق
      # ======================
      - name: 🛠️ بناء حزمة التطبيق
        script: |
          flutter pub get
          flutter build appbundle --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --obfuscate \
            --split-debug-info=./debug_info
          echo "✔ تم البناء بنجاح"

      # ======================
      # 3. نشر على Firebase
      # ======================
      - name: 📤 النشر على Firebase
        script: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            build/app/outputs/bundle/release/*.aab \
            --app $FIREBASE_APP_ID \
            --token "$FIREBASE_TOKEN" \
            --groups "testers"
          echo "✔ تم النشر على Firebase بنجاح"

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - debug_info/

    publishing:
      email:
        recipients:
          - "gogom8870@gmail.com"  # ⚠️ استبدل بريدك الفعلي
        notify:
          success: true
          failure: true
