workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:
        FLUTTER_VERSION: "3.19.5"
        # تعريف متغيرات Firebase مباشرة (بدلاً من المجموعات)
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    triggering:
      events: [push]
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      # ===================================
      # 1. إعداد البيئة الأساسية
      # ===================================
      - name: 🛠️ إعداد البيئة
        script: |
          flutter version $FLUTTER_VERSION
          flutter doctor -v
          
          # حل جذري لمشكلة Firebase CLI
          npm config set prefix ~/.npm-global
          echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc
          npm install -g firebase-tools@latest --force
          firebase --version

      # ===================================
      # 2. بناء APK بدون توقيع
      # ===================================
      - name: 🏗️ بناء APK
        script: |
          flutter clean
          flutter pub get
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --split-debug-info=./debug_info
          
          # التحقق من المخرجات
          ls -la build/app/outputs/flutter-apk/
          APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✔ تم البناء بنجاح! حجم الملف:"
            du -h "$APK_PATH"
          else
            echo "❌ فشل في إنشاء ملف APK"
            exit 1
          fi

      # ===================================
      # 3. النشر على Firebase
      # ===================================
      - name: 📤 نشر على Firebase
        script: |
          # إنشاء ملف Service Account مؤقت
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/service-account.json
          
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --service-account-json /tmp/service-account.json \
            --groups "testers" \
            --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - debug_info/**
    publishing:
      email:
        recipients:
          - "your-email@example.com" # ⚠️ استبدل بريدك الفعلي
        notify:
          success: true
          failure: true
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
