workflows:
  production:
    name: WiMax Production Build
    environment:
      groups:
        - keystore_credentials
        - firebase_config
      vars:
        FCI_KEYSTORE_PATH: "android/app/keystore/keystore.jks"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Decode Keystore
        script: |
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
          scripts:
      - name: Set up keystore
        script: |
         mkdir -p android/app/keystore
         echo $FCI_KEYSTORE | base64 --decode > android/app/keystore/keystore.jks
         chmod 600 android/app/keystore/keystore.jks
      - name: Build Android
        script: |
          flutter pub get
          flutter build appbundle --release --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - your_email@example.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
