workflows:
  android_production:
    name: 🚀 Android Production Build
    environment:
      vars:
        FLUTTER_VERSION: "3.32.4"
        GRADLE_VERSION: "7.5"  # تم التغيير إلى إصدار متوفر
        KOTLIN_VERSION: "1.7.20"
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    
    scripts:
      - name: ⬇️ تثبيت Flutter
        script: |
          export FLUTTER_HOME="$HOME/programs/flutter"
          rm -rf $FLUTTER_HOME
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION $FLUTTER_HOME
          export PATH="$FLUTTER_HOME/bin:$PATH"
          flutter doctor -v

      - name: 🛠️ إعداد Gradle (الطريقة المؤكدة)
        script: |
          if [ ! -d "android" ]; then
            flutter create --platforms android .
          fi
          
          # إنشاء ملف build.gradle المعدل
          echo "buildscript {
            ext {
                kotlin_version = '$KOTLIN_VERSION'
            }
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()  # أضيف هذا السطر
            }
            dependencies {
                classpath 'com.android.tools.build:gradle:$GRADLE_VERSION'
                classpath \"org.jetbrains.kotlin:kotlin-gradle-plugin:\$kotlin_version\"
            }
          }

          allprojects {
            repositories {
                google()
                mavenCentral()
            }
          }

          task clean(type: Delete) {
            delete rootProject.buildDir
          }" > android/build.gradle

          # استخدام توزيعة Gradle مباشرة من services.gradle.org
          echo "distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists" > android/gradle/wrapper/gradle-wrapper.properties
          
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          chmod +x android/gradlew

      - name: 🔄 تحديث التبعيات
        script: |
          flutter pub get
          cd android && ./gradlew clean --stacktrace --refresh-dependencies && cd ..

      - name: 🏗️ بناء APK
        script: |
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID \
            --verbose

      - name: 🚀 النشر على Firebase
        script: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase_account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --service-account-json /tmp/firebase_account.json
    
    artifacts:
      - build/app/outputs/**/*.apk
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
