workflows:
  secure_release:
    name: Secure Release Build
    environment:
      groups:
        - signing_credentials
      vars:
        FCI_KEYSTORE_PATH: "android/app/keystore/keystore.jks"  # سيتم إنشاؤه
    triggering:
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Setup Keystore from Env
        script: |
          mkdir -p android/app/keystore
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
          chmod 600 $FCI_KEYSTORE_PATH
          
          # التحقق من صحة الملف
          keytool -list -v \
            -keystore $FCI_KEYSTORE_PATH \
            -storepass $KEYSTORE_PASSWORD \
            -alias $KEY_ALIAS || {
              echo "❌ Keystore validation failed";
              exit 1;
            }

      - name: Build App Bundle
        script: |
          flutter pub get
          flutter build appbundle --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID

      - name: Cleanup Keystore
        script: |
          rm -f $FCI_KEYSTORE_PATH
          echo "🔒 Keystore removed successfully"
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
      email:
        recipients:
          - your.email@example.com