workflows:
  android-release:
    name: Android Release Workflow
    environment:
      vars:
        FLUTTER_VERSION: "3.32.4"
      flutter: $FLUTTER_VERSION
    scripts:
      - name: Clean Environment
        script: |
          echo "=== تنظيف البيئة ==="
          flutter clean
          rm -rf android/.gradle
          rm -rf ~/.gradle/caches

      - name: Setup Flutter
        script: |
          echo "=== إعداد Flutter ==="
          flutter channel stable
          flutter upgrade --force
          flutter pub get

      - name: Build APK
        script: |
          echo "=== بناء APK ==="
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
