################################################################
# WiMax Security Tester - Flutter Build Configuration
# تم التحديث ليعمل مع مجموعات المتغيرات الحالية
################################################################

workflows:
  android_production:
    name: Android Production Build
    environment:
      groups:
        - signing_credentials  # يجب أن يكون الاسم مطابقًا تمامًا لما في Codemagic
        - firebase_config      # يجب أن يكون الاسم مطابقًا تمامًا لما في Codemagic
      vars:
        PACKAGE_NAME: "com.example.wimax"  # استبدل باسم حزمة تطبيقك
        
    scripts:
      # [1] إعداد توقيع Android
      - name: 🔐 Prepare Keystore
        script: |
          mkdir -p android/app/keystore
          echo $ENCODED_KEYSTORE | base64 --decode > android/app/keystore/release.jks
          keytool -list -v \
            -keystore android/app/keystore/release.jks \
            -storepass $STORE_PWD \
            -alias $KEY_ALIAS

      # [2] البناء
      - name: 🛠️ Build App Bundle
        script: |
          flutter pub get
          flutter build appbundle --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID

    artifacts:
      - build/app/outputs/bundle/release/*.aab
