workflows:
  android_production:
    name: ðŸš€ Android Production Build
    environment:
      vars:
        FLUTTER_VERSION: "3.22.2"
        GRADLE_VERSION: "8.1.0"
        KOTLIN_VERSION: "1.9.22"
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_APP_ID: $FIREBASE_APP_ID
        FIREBASE_SERVICE_ACCOUNT_JSON: $FIREBASE_SERVICE_ACCOUNT_JSON
    
    scripts:
      - name: â¬‡ï¸ ØªØ«Ø¨ÙŠØª Flutter
        script: |
          export FLUTTER_HOME="$HOME/programs/flutter"
          rm -rf $FLUTTER_HOME
          git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION $FLUTTER_HOME
          export PATH="$FLUTTER_HOME/bin:$PATH"
          flutter doctor -v

      - name: ðŸ”§ Ø¥Ø¹Ø¯Ø§Ø¯ Ø§Ù„Ù…Ø´Ø±ÙˆØ¹
        script: |
          echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
          echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties
          sed -i '' "s/gradle-.*.zip/gradle-$GRADLE_VERSION-bin.zip/g" android/gradle-wrapper.properties

      - name: ðŸ—ï¸ Ø¨Ù†Ø§Ø¡ APK
        script: |
          flutter pub get
          flutter build apk --release \
            --dart-define=FIREBASE_API_KEY=$FIREBASE_API_KEY \
            --dart-define=FIREBASE_APP_ID=$FIREBASE_APP_ID

      - name: ðŸš€ Ø§Ù„Ù†Ø´Ø± Ø¹Ù„Ù‰ Firebase
        script: |
          echo "$FIREBASE_SERVICE_ACCOUNT_JSON" > /tmp/firebase_account.json
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID \
            --groups "testers" \
            --service-account-json /tmp/firebase_account.json
    
    artifacts:
      - build/app/outputs/**/*.apk
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
