name: wimax_pentest_flutter
description: تطبيق متكامل لاختبار اختراق شبكات WiMax مع أدوات الهجوم المدمجة

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  firebase_core: ^2.18.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # إدارة الحالة
  provider: ^6.1.1
  riverpod: ^2.3.6

  # الشبكات والأدوات
  wifi_scan: ^0.8.1
  network_tools: ^1.1.2
  flutter_shell: ^0.3.0

  # الأذونات
  permission_handler: ^10.4.0
  android_intent_plus: ^7.0.1

  # الواجهة
  flutter_staggered_animations: ^1.1.0
  console: ^1.0.0
  animated_text_kit: ^4.2.2

  # التقارير والبيانات
  pdf: ^3.10.2
  excel: ^2.0.0
  csv: ^5.0.1

  # اتصال Native
  ffi: ^2.0.1
  jni: ^0.21.1

  # Utilities
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  dio: ^5.3.0
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/attacks/
    - assets/images/networks/
    - assets/tools/armeabi-v7a/
    - assets/tools/arm64-v8a/
    - assets/tools/x86/
    - assets/tools/x86_64/
    - assets/wordlists/
    - assets/fonts/

  fonts:
    - family: Hacker
      fonts:
        - asset: assets/fonts/hacker.ttf
    - family: Monospace
      fonts:
        - asset: assets/fonts/consolas.ttf

  # إعدادات Android
  android:
    package: com.wimax.pentest
    enable_jetifier: true
    permissions:
      - android.permission.ACCESS_WIFI_STATE
      - android.permission.CHANGE_WIFI_STATE
      - android.permission.ACCESS_NETWORK_STATE
      - android.permission.ACCESS_FINE_LOCATION
      - android.permission.ACCESS_COARSE_LOCATION
      - android.permission.INTERNET
      - android.permission.ACCESS_SUPERUSER

  # إعدادات iOS
  ios:
    info.plist:
      UIBackgroundModes:
        - network-authentication
      NSLocationWhenInUseUsageDescription: "Required for WiMax scanning"
      NSLocationAlwaysAndWhenInUseUsageDescription: "Required for continuous scanning"
      NSLocationAlwaysUsageDescription: "Required for background scanning"