name: wimax_security_tester
description: A security testing app for WiMAX networks.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_analytics: ^11.5.0

  # Network
  connectivity_plus: ^6.1.4
  http: ^1.2.1

  # Network Scanning (بديل موثوق)
  arp_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.0.0
