name: wimax_security_tester
description: WiMax Security Tester Application

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  # أضف باقي التبعيات هنا

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # تجنب وضع إعدادات android/ios هنا مباشرة
