name: wimax_security_tester
description: WiMax Security Tester Application

# Versioning (Major.Minor.Patch+Build)
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase Dependencies
  firebase_core: ^2.15.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.1.0
  
  # Essential Packages
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  dio: ^5.3.3
  
  # UI & Utilities
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/fonts/
  
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
